query initializeApp {
  subscriberSettings {
    id
    networkId
  }
  postTypes(limit: 15) {
    nodes {
      name
      id
    }
  }
  spaces(limit: 30) {
    nodes {
      id
      name
      imageId
    }
  }
}
