query postList(
  $offset: Int!
  $limit: Int!
  $orderByString: String
  $reverse: Boolean
  $query: String
) {
  posts(
    offset: $offset
    limit: $limit
    orderByString: $orderByString
    reverse: $reverse
    query: $query
  ) {
    nodes {
      id
      title
      owner {
        member {
          name
        }
      }
      space {
        name
      }
      createdAt
      reactionsCount
      totalRepliesCount
    }
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

mutation createPost($input: CreatePostInput!, $spaceId: ID!) {
  createPost(input: $input, spaceId: $spaceId) {
    status
    id
  }
}
