query postList(
  $offset: Int!
  $limit: Int!
  $orderByString: String
  $reverse: Boolean
  $query: String
) {
  posts(
    offset: $offset
    limit: $limit
    orderByString: $orderByString
    reverse: $reverse
    query: $query
  ) {
    nodes {
      id
      title
      createdBy {
        member {
          name
        }
      }
      space {
        name
      }
      createdAt
      reactionsCount
      totalRepliesCount
    }
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query PostDetail($id: ID!) {
  post(id: $id) {
    id
    title
    contentSummary(length: 20000) {
      summary
    }
    createdAt
    reactionsCount
    createdBy {
      member {
        name
      }
    }
    space {
      name
      imageId
    }
    reactions {
      reacted
      reaction
      count
    }
  }
}

mutation addPostReaction($id: ID!, $reaction: String!) {
  addReaction(
    postId: $id
    input: { overrideSingleChoiceReactions: true, reaction: $reaction }
  ) {
    status
  }
}

mutation removePostReaction($id: ID!, $reaction: String!) {
  removeReaction(postId: $id, reaction: $reaction) {
    status
  }
}

mutation createPost($input: CreatePostInput!, $spaceId: ID!) {
  createPost(input: $input, spaceId: $spaceId) {
    status
    id
  }
}
